service: serverless-auth

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-aws-documentation
  - serverless-domain-manager

provider:
  name: aws
  stage: dev
  region: us-east-2
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["UsersDynamoDBTable", "Arn"] }
  environment:
    USERS_TABLE: ${self:custom.tableName}
    INDEX_NAME: ${self:custom.indexName}
    NODE_ENV: ${self:provider.stage}
    ACCESS_TOKEN_SECRET: ${env:ACCESS_TOKEN_SECRET}
    REFRESH_TOKEN_SECRET: ${env:REFRESH_TOKEN_SECRET}

functions:
  auth:
    handler: handler.server
    events:
      - http:
          path: /login
          method: post
      - http:
          path: /register
          method: post

resources:
  Resources:
    UsersDynamoDBTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: ${self:custom.indexName}
            KeySchema:
              - AttributeName: username
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1

custom:
  tableName: "users-table-${self:provider.stage}"
  indexName: "UserDetail"
  customDomain:
    domainName: auth.saipathuri.me
    basePath: api
    certificateName: "auth.saipathuri.me"
    createRoute53Record: true
    endpointType: "regional"
    securityPolicy: tls_1_2
  documentation:
    api: ${file(docs/swagger.yml)}
